name: Martabux
favicon: null
layout_spectrum: 0.06933671236038208
typography_spectrum: 0.24149355106055737
title: 'Great Taste to Remember, Sweet Martabak, Savory Martabak, Mini Martabak, Cold Brew Coffee, Nitro Coffee'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000009'
    - '#fefefe'
    - '#92958c'
    - '#884b46'
    - '#e36c8f'
  brandStrength: 0.5
  lightness: 0.4594899488147348
  saturation: 0.41384255583398044
  rhythmicContrast: 0.10982155287638307
purpose: []
