name: Martabux
favicon: null
layout_spectrum: 0.23777
typography_spectrum: 0.24149355106055737
title: 'Great Taste to Remember, Sweet Martabak, Savory Martabak, Mini Martabak, Cold Brew Coffee, Nitro Coffee'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00552b'
    - '#7f6c72'
    - '#b7a3ae'
    - '#b0d587'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
